### ISSUE TITLE
Incorrect result on partial dev set

### ISSUE THREAD

**Issue by roastduck** [allenai/longformer#69] opened 2020-06-22 10:31 UTC
I ran the test on part of the dev set of TriviaQA, getting an incorrect result.

Specifically, I did the following steps:

1. I ran the test on the full dev set as per `cheatsheet.txt`, and got a `prediction.txt`, say `prediction.txt.full`.
2. I used the `--sample_size` argument of `scripts/triviaqa_utils/convert_to_squad_format.py` to retrieve the first 500 samples from the dev set. I ran it and got a `prediction.txt`, say `prediction.txt.part`.
3. I compared `prediction.txt.full` and `prediction.txt.part`, finding most of the answers are the same, but a significant part (around 1/6) of them are different.

I also tried fp32, and the results are still different.

Is something related to the data set size hard-encoded into the code? How do I correctly run part of the samples.

**Comment by ibeltagy** [comment] 2020-06-24 20:50
Yes, this is expected and it is not a bug. Some TriviaQA questions have more than one associated document. The model extracts an answer from each document, group the answers by question id, then keep the answer with the top score. Each question/document pair is one sample, so when you limit the sample size, you run into the situation where some of the question documents are in the sample and some documents are not, which results in different answers.

**Comment by ibeltagy** [comment] 2020-09-12 19:48
Closing. Please feel free to reopen if needed.

**Closed by ibeltagy** 2020-09-12 19:48 UTC
