### ISSUE TITLE
Convert XLM-RoBERTa to long version

### ISSUE THREAD

**Issue by samru-rai** [allenai/longformer#85] opened 2020-07-13 13:29 UTC
RoBERTa is currently monolingual. Can we make it talk multiple languages by converting XLM-RoBERTa (https://arxiv.org/pdf/1911.02116.pdf) to long version? There seems to already exists pre-trained version of the model https://huggingface.co/transformers/multilingual.html#xlm-roberta. 

There has been some discussion to create multi-lingual RoBERTa https://github.com/pytorch/fairseq/issues/952 and the issue seems to close by pointing to https://github.com/pytorch/fairseq/tree/master/examples/xlmr

**Comment by ibeltagy** [comment] 2020-07-13 14:22
duplicate of https://github.com/allenai/longformer/issues/21

**Closed by ibeltagy** 2020-07-13 14:22 UTC
